### ISSUE TITLE
Program La relance

### ISSUE THREAD

**Issue by VezensekKaja** [ZilavecM14/Poker-1.skupina#1]
Zanima naju, če najin program za 'La relance' dejansko vzame vse zgnenerirana števila iz vektorjev X in Y, ter če to stori po vrsti. Ko sva namreč nekajkrat zagnali program se dobljene vrednosti za 1. igralca (R1) in za 2. (R2) dobili negativna števila. Ko sva spremenili, da naj R1 in R2 dejansko shranjuje na prava mesta v vektorih (da se rezultat na mestu npr. 50, ujema s 50 igro), pa za R1 in R2 dobiva prazna vektora.

**Comment by VezensekKaja** [comment]
Sva ugotovili problem številčenja, sedaj pa ne veva zakaj nama za R2 nikoli ne zgenerira B+1 oziroma -(B+1) vedno vzame samo +1 ali -1. Čeprav bi moral v primeru, ko je R1 pokazal B+1 R2 pokazati -(B+1), R1 pa zgenerira pravilno

**Comment by jaanos** [comment]
Pazita na zavite oklepaje pri `else` - če jih ni, potem se bo v primeru neizpolnjevanja pogoja pri `if` izvedla le prva vrstica za `else`, sledeče vrstice pa so izven stavka `if/else` in se torej izvedejo v vsakem primeru (podobno seveda velja tudi za ostale konstrukte).

Mimogrede, trenutno imata
```R
  for (x in X[i]){
    for (y in Y[i]){
```
Ker sta `X[i]` in `Y[i]` vektorja dolžine 1, ti zanki naredita samo en korak. Ekvivalentno in bolj berljivo bi bilo napisati
```R
  x <- X[i]
  y <- Y[i]
```
ali pa enostavno zamenjati pojavitve `x` in `y` z `X[i]` oziroma `Y[i]`.

Še to: svetujem, da v imenih datotek nimata presledkov, saj potem deluje [neposredno citiranje kode](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/) v issuejih - tako sem moral zgornjo kodo kopirati.

**Comment by VezensekKaja** [comment]
Pozdravljeni,
Zanima naju, če imava napisanega dovolj programa oziroma, kaj lahko še dodava/spremeniva.

**Comment by VezensekKaja** [comment]
Radi bi še spreminjali velikost stav B in primerjali grafe za posamezne stave. Zanima naju kako to storiva optimalno, saj če dodava da je B vektor z različnimi vrednostmi to pokvati najine zanke.

**Comment by jaanos** [comment]
Če prav vidim, imata trenutno implementirani optimalni strategiji iz članka. Da preverita, ali se res izkažeta za optimalni, bo treba implementirati še alternativne strategije - potem lahko delata simulacije, kjer se en igralec drži optimalne strategije, drugi pa ne, in primerjata dobljene rezultate.

Za alternativne strategije lahko vzameta npr. naključne stave, ali pa verjetnostno različico optimalne strategije (namesto, da igralčeva vrednost določa, ali bo stavil ali odstopil, naj bo meja ravno verjetnost odstopa). Svetujem, da si strategije pripravita kot funkcije - če funkcija vrne `TRUE`, to pomeni, da igralec stavi oz. izenači, npr.
```R
# optimalna strategija za prvega igralca pri La Relance
LaRelance.opt1 <- function(X, c1) {
  return(X > c1^2)
}
```
Potem lahko napišeta še funkcije, ki izvedejo simulacije pri danih parametrih in strategijah, npr.
```R
LaRelance <- function(st1, st2, B, n = 100) {
  X <- runif(n, min=0, max=1)
  Y <- runif(n, min=0, max=1)
  c1 <- B/(B+2)
  # karkoli še pač potrebujeta
  for (i in 1:n){
    if (st1(X[i], c1)) { #prvi igralec je stavil
      if (st2(Y[i], c1)) {
        # drugi igralec je stavil
      } else {
        # drugi igralec je odstopil
      }
    } else {
      # prvi igralec je odstopil
    }
  }
  # končni izračuni, risanje grafov
}
```
Tako lahko kličeta npr.
```R
LaRelance(LaRelance.opt1, LaRelance.opt2, B)
```
`B` je tukaj posamezna vrednost - če želita dobiti podatke za več različnih vrednosti, lahko zgornji klic opravita v zanki `for`, ali pa kar z npr. `sapply` (če bo program vračal končni dobiček - dovolj bi sicer moralo biti za enega igralca).

**Comment by VezensekKaja** [comment]
Hvala za pomoč, bova spremenili.
Sedaj sva prenesli in bi radi, da nama funkcija vrne dobiček in število zmag. Ko funkcijo kličeva nama ne izpiše ničesar, razen grafa, čeprav sva željene stvari napisale na koncu 'for' zanke.

**Comment by jaanos** [comment]
Zadnja vrstica v funkciji je risanje grafa. Če želita, da vama vrne želeni vrednosti, za risanjem grafa dodajta še
```R
  return(c(Z1, sum(R1)))
```
Tako bo rezultat funkcije vektor z dvema elementoma. Seveda bi šlo tudi brez `return`, a je v funkcijah, ki zajemajo več kot samo kakšno vrstico, bolj jasno, če se ga eksplicitno uporabi.

**Comment by VezensekKaja** [comment]
Hvala, sedaj deluje.
Dodali sva še funkciji karkoli1 in karkoli2, ki predstavljata naključni števili pri katerih se igralca odločita da stavita oziroma odstopita. Sedaj je problem samo, ker ne veva, če sva to pravilno vključile v glavno funkcijo LaRelance, torej ali končne vrednosti, ki jih dobiva, če kličeva npr. LaRelance(LaRelance.opt1, Karkoli2, 10), upoštevajo najino naključnost, glede na to, da imajo 'if' stavki še vedno vsebovano spremenljivko c1.

**Comment by jaanos** [comment]
Trenutno sta funkciji `karkoli1` in `karkoli2` enakovredni funkciji `LaRelance.opt2`. Ker se funkcije kličejo z dvema parametroma, ju bo morala tudi funkcija za naključno izbiro sprejeti, a ju lahko potem ignorira, npr.
```R
nakljucno <- function(X, c1) {
  return(runif(1) > 0.5)
}
```
Taka funkcija torej z verjetnostjo 0.5 vrne `TRUE`, saj `runif` privzeto vrača enakomerno naključne vrednosti z intervala [0, 1].

**Comment by VezensekKaja** [comment]
Sva popravili in dodali še strategijo, kjer stavita, če je X oziroma Y večji od 1/2.
Zanima naju, če so sedaj strategije vredu, sploh pri Von Neumnannu, kjer je v funkcijah uporabljena več kot ena spremenljivka (a in b).
Ali morava še kaj dodati?

**Comment by jaanos** [comment]
Strategije izgledajo v redu napisane, tako da lahko poskusita, kaj se dogaja, ko igrata različne strategije eno proti drugi (če seveda še nista). Opozoril bi le na strategijo `nakljucnoPrvi` v `VonNeumann.R` - trenutno se preverjata dve neodvisni slučajni spremenljivki; če poračunata verjetnost uspeha, dobita 0.55. Če želita verjetnost 0.6, bo lažje enostavno napisati `runif(1) > 0.4`.

Morda bi predlagal še takšno strategijo (v primerih, ko imata eno mejno vrednost): če je `X` enak, je verjetnost stave 0; če je `X` enak mejni vrednosti (torej `c1` ali `c1^2`), je verjetnost stave 0.5; če pa je `X` enak 1, pa je verjetnost stave 1. V vseh vmesnih vrednostih lahko potem verjetnost interpolirata: lahko linearno (torej bo funkcija verjetnosti v odvisnosti od `X` sestavljena iz dveh linearnih odsekov), ali pa kvadratno (funkcija verjetnosti bo enolično določena kvadratna funkcija s prej omenjenimi lastnostmi).

Za primer z dvema mejnima vrednostma bo to nekoliko bolj zapleteno: načeloma bi želeli verjetnost stave 1, če je `X` enak 0 ali 1, ter verjetnost 0.5, če je `X` enak mejnima vrednostma. Če bi se šli linearne interpolacije, bi morali paziti, da je v območju med mejnima vrednostma verjetnost manjša od 0.5 - lahko bi določili točko, kjer je verjetnost 0 (in tako imeli 4 linearne odseke), ali pa bi enostavno linearna odseka s krajišč potegnili skozi mejni vrednosti do njunega presečišča. Druga možnost je seveda, da bi funkcija verjetnosti bila kubična funkcija z želenimi lastnostmi.

**Comment by VezensekKaja** [comment]
Sva dodali še interpolacijo, ampak iz nama neznanega razloga ne dela. V funkciji sva definirali if stavek, ki določa na katerem odseku smo. Kje je problem?

**Comment by jaanos** [comment]
`runif(c1)` vrne vektor s `c1` enakomerno naključnih vrednosti z intervala [0, 1]. Če želita eno naključno vrednost z intervala [0, `c1`], uporabita `runif(1, min = 0, max = c1)`.

**Comment by VezensekKaja** [comment]
Sva popravili in dodali še za Von Neumannov model, potrebujeva dodati še kaj?

**Comment by jaanos** [comment]
Še to: `runif(1, min = (c1),max=1) > 0.1*(1-c1)` bo vedno `TRUE`, kot je `c1 > 1/11`. Ideja je bila, da imata pri `X == c1` verjetnost 0.5, pri `X == 1` pa verjetnost 1. To bi šlo nekako tako:
```R
runif(1, min = c1, max = 1) < (X+1)/2
```
Podobno bi seveda bilo treba narediti še v ostalih primerih. Seveda lahko strategijo tudi priredita, če se vama zdi smiselno.

Drugače pa imata po mojem dovolj strategij, da lahko izvedeta simulacije in na podlagi rezultatov napišeta končno poročilo.

**Comment by VezensekKaja** [comment]
Sva popravili primerjalne vrednosti. Prosiva samo, da preverite, če so sedaj smiselne.
Hvala

**Comment by jaanos** [comment]
So v redu, z izjemo primerov, ko je `a < X < b` pri Von Neumannovem modelu. Da bi dosegli verjetnost 0.5 pri `X == a` in `X == b` ter verjetnost 0 pri `X == (a+b)/2`, bi morali imeti
```R
  else if (X>=a & X<(a+b)/2){
    return(runif(1, min = a, max=(a+b)/2) > (X + (a+b)/2)/2)
  }
  else if (X>=(a+b)/2 & X<b){
    return(runif(1, min = (a+b)/2, max=b) < (X + (a+b)/2)/2)
  }
```
Ideja je torej ta, da če vstavimo enega od krajišč intervala, se na desni strani poračuna ravno njegova sredina in je zato verjetnost 0.5, če pa vstavimo drugega, se izračuna ta ista vrednost in je torej verjetnost enaka 0 ali 1 - odvisno od tega, kako primerjamo.

Mimogrede, pri primerjavah sem dodal možnost, da pride do enakosti - ker računalnik dela s števili z omejeno natančnostjo, verjetnost enakosti ni enaka 0, kakor bi to veljalo za realna števila. Tako je treba tudi za mejne vrednosti poskrbeti, da padejo pod ustrezni pogoj.

**Comment by VezensekKaja** [comment]
Sem popravila še to. Hvala za vso pomoč.
